version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default
  backend:
    image: nikmodenov/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    networks:
      - default
  frontend:
    env_file: .env
    image: nikmodenov/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    networks:
      - default
  gateway:
    image: nikmodenov/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    networks:
      - default

networks:
  default:
    driver: bridge
